name: Recent GitHub Activity
on:
  schedule:
    #Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-activity:
    name: Update this repo's README with the latest GitHub activity
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/latest-github-activity@master
        with:
          feed_list: "https://github.com/EternityRei"
